### ISSUE TITLE
webpack: Failed to compile.

### ISSUE THREAD

**Issue by Vetnametz** [godbasin/angular-select2#1]
ERROR in .../node_modules/angular4-select2/src/select2.component.ts (6,1): Cannot find name 'require'.

ERROR in .../node_modules/angular4-select2/src/select2.component.ts (8,59): Cannot find module './custom-input'.

ERROR in .../node_modules/angular4-select2/src/select2.component.ts (31,43): Property 'value' does not exist on type 'Select2Component'.

ERROR in .../node_modules/angular4-select2/src/select2.component.ts (39,18): Property 'value' does not exist on type 'Select2Component'.

ERROR in ./~/angular4-select2/src/select2.component.ts
Module not found: Error: Can't resolve './custom-input' in '.../node_modules/angular4-select2/src'
 @ ./~/angular4-select2/src/select2.component.ts 22:0-75
 @ ./~/angular4-select2/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

**Comment by godbasin** [comment]
Sorry about the bugs with `angular4-select2` npm-package.
The package is no longer supported. It changes to [`angular-select2-component`](https://www.npmjs.com/package/angular-select2-component). Maybe you could try it.

Thanks for your issues!
