### ISSUE TITLE
im not able to set default value

### ISSUE THREAD

**Issue by rajhim** [godbasin/angular-select2#12]
how to show selected value in ngModel ? in first?

**Comment by godbasin** [comment]
`ngModel` is a two-way binding directive. So you just need to give your variable a value, it will auto select the value.

For example, you can make it change when `ngOnInit` is fired.
``` javascript
@Component({
  selector: 'app-root',
  templateUrl:
    '<select2 [options]="options" [(ngModel)]="optionSelected"></select2>'
})
export class AppComponent implements OnInit {
  options: any[] = ['1-1', '1-2', '1-3', '1-4', '1-5'];
  optionSelected: any;

  ngOnInit() {
    this.optionSelected = '1-1';
  }
}
```

**Comment by rajhim** [comment]
if its in key value pair ? how should i set ?

**Comment by godbasin** [comment]
We use `{id, text}` pair in [select2](https://select2.org/data-sources/formats).

**Comment by rajhim** [comment]
how to set default can u give example ?

**Comment by godbasin** [comment]
``` javascript
@Component({
  selector: 'app-root',
  templateUrl:
    '<select2 [options]="options" [(ngModel)]="optionSelected"></select2>'
})
export class AppComponent implements OnInit {
  options: any[] = [{id: '1-1value', text: '1-1key'}, {id: '1-2value', text: '1-2key'}, {id: '1-3value', text: '1-3key'}];
  optionSelected: any;

  ngOnInit() {
    this.optionSelected = '1-2value';
  }
}
```

Could you please clone the [demo](https://github.com/godbasin/angular-select2) and run it on your machine? Any more question, please put your code here.

**Comment by rajhim** [comment]
can i keep placeholder for this? Thankyou in advance

**Comment by godbasin** [comment]
You can set the placeholder through `settings`, see [Select2 options API](https://select2.org/configuration/options-api).

**Comment by rajhim** [comment]
hello, thankyou for support, i have done for setting default value: like this, 

@Component({
  selector: 'app-root',
  templateUrl:
    '<select2 [options]="options" [(ngModel)]="optionSelected"></select2>'
})
export class AppComponent implements OnInit {
  options: any[] = [{id: '1-1value', text: '1-1key'}, {id: '1-2value', text: '1-2key'}, {id: '1-3value', text: '1-3key'}];
  optionSelected: any;

  ngOnInit() {
    this.optionSelected = this.options[0].text;
  }
}
 its not showing value ? help me

**Comment by godbasin** [comment]
You should bind `ngModel` to the value. That means to use `this.optionSelected = this.options[0].id;` instead of `this.optionSelected = this.options[0].text;`.
