### ISSUE TITLE
Error when building 1.1.2 version

### ISSUE THREAD

**Issue by taikodragon** [godbasin/angular-select2#18]
ERROR in node_modules/angular-select2-component/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts
(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

The issue is that a node_modules directory was included in the npm publish.

**Comment by godbasin** [comment]
Is it the same situation with [https://github.com/angular/angular/issues/21670](https://github.com/angular/angular/issues/21670). It seems to be something about the version. 

Please try to fix it with the solution there. If it still happens, please offer more detail about your angular/typescript/node version, and a demo will help the best. Thanks.
