### ISSUE TITLE
Error while building 

### ISSUE THREAD

**Issue by rajhim** [godbasin/angular-select2#19]
ERROR in Error: Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Component..

/node_modules/angular-select2-component/src/select2.component.ts

**Comment by rajhim** [comment]
ng build --prod u can check by this

**Comment by godbasin** [comment]
It seems that I've mixed something experimental up in my package. Please try version 1.1.3.
And `ng build --prod` is not supported now because I haven't make it compatible with AOT. So It only works with `ng build` without production. :sob: :

**Comment by rajhim** [comment]
so when u r gona update for prod ?

**Comment by rajhim** [comment]
ERROR Error: Uncaught (in promise): Error: StaticInjectorError[ElementRef]: 
  StaticInjectorError[ElementRef]: 
    NullInjectorError: No provider for ElementRef!
Error: StaticInjectorError[ElementRef]: 
  StaticInjectorError[ElementRef]: 
    NullInjectorError: No provider for ElementRef!    



what is this error ???????

**Comment by rajhim** [comment]
iam not able to solve this problem ...

**Comment by godbasin** [comment]
> ERROR Error: Uncaught (in promise): Error: StaticInjectorError[ElementRef]:
> StaticInjectorError[ElementRef]:
> NullInjectorError: No provider for ElementRef!
> Error: StaticInjectorError[ElementRef]:
> StaticInjectorError[ElementRef]:
> NullInjectorError: No provider for ElementRef!

This seems to be something missing in your project. Do you have a demo?

**Comment by godbasin** [comment]
And I don't have experience with AoT. It might take times.
