### ISSUE TITLE
Add On Feature ( OnMouseOver )

### ISSUE THREAD

**Issue by lorocongo** [godbasin/angular-select2#20]
Hi, i come across a need in your project to fire a onMouseOver event to change a external div with an avatar.

My suggestion :
Add to select2Component

line 35 :   
    @Output() onMouseOver = new EventEmitter<any>();

line 90: 
      this.select2.on('select2:mouseover', (ev: any) => {
        const selectValue = this.select2.val();
        this.value = selectValue;
        const { id, text, selected } = ev['params']['data'];
        this.onMouseOver.emit({ id, text, selected });
      });

add to select2.js

line 2052:
    var relayEvents = [
      'open', 'opening',
      'close', 'closing',
      'select', 'selecting',
      'unselect', 'unselecting',
      'mouseover', 'mouseover'
    ];

line 1158:
    container.on('results:focus', function (params) {
      params.element.addClass('select2-results__option--highlighted');
      var data = params.data;
      self.trigger('mouseover', {
          data: data
        });
    });

this will catch the native event mouseover and send it to the component

<select2 [options]="options" [settings]="{ setting: value }" [(ngModel)]="optionSelected" (onSelect)="onSelect($event)"
(onMouseOver)="onMouseOver($event)" ></select2>

Hope you can add it to the code.

**Comment by godbasin** [comment]
I think you should make a pull request to [select2](https://github.com/select2/select2) for this new feature. It's better to keep the official version in my project.

**Comment by lorocongo** [comment]
Already done!!

sorry for all the pull requests, first time.

**Comment by godbasin** [comment]
You should make a pull request to [select2](https://github.com/select2/select2) for this new feature. And you should consider those who don't use `onMouseOver` event, this may cause extra executed statements.
