### ISSUE TITLE
Badly packed library?

### ISSUE THREAD

**Issue by ohokke** [godbasin/angular-select2#26]
Hey there, wanted to use your plugin, but I got the following error:

`ERROR in ./node_modules/angular-select2-component/index.ts
Module build failed: Error: C:\Olivier\Work\Orbit Games\Projects\JSON Database Editor\json-database-editor\node_modules\angular-select2-component\index.ts is missing from
the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a
badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).`

**Comment by godbasin** [comment]
Adding the include option at the end of tsconfig.json fixed the compile issue. 
Similar to #2 

See [Compile settings](https://github.com/godbasin/angular-select2#use-as-component) for more detail.
