### ISSUE TITLE
Setting language -> "noResults"

### ISSUE THREAD

**Issue by nobady90** [godbasin/angular-select2#27]
Hi guys, you did a great job to implement select2 in angular!

The only thing that at the moment I can not do is to change the words "No results found", because the setting to do it is "noResults" but it is under the control of the "language" setting, in this way :

"Language": {
           "noResults": "new string instead of No result found"
         }

I tried in various ways to insert it into [settings] but without success, has anyone already solved this? is there a way to do it?

**Comment by godbasin** [comment]
You may use a object to provide your own custom messages like this:
```
language: {
    noResults: () => "new string instead of No result found"
}
```
See [Message translations](https://select2.org/i18n#message-translations) for more detail。
