### ISSUE TITLE
TypeError: this.onChange is not a funktion

### ISSUE THREAD

**Issue by olehvic** [godbasin/angular-select2#29]
Hey, 
your select-2-component is really nice, it works but i can not read the selected values from dropdown because  i have an client error in **/node_modules/angular-select2-component/src/custom-input.ts** by selecting the value from dropdown. Debugger from chrome-dev-tools says that  this.onChange is not a funktion at this place in code and it crashes: 
`  set value(v: any) {
    if (v !== this.model) {
      this.model = v;
      this.onChange(v);
    }
  }`
I use Angular Version: 5.1.2 and webpack.

**Comment by godbasin** [comment]
Please provide more detail or a demo to show how you use it.

**Comment by olehvic** [comment]
Hey @godbasin ,

sorry for the issue. This was my fault. I tried to implement the dropdown in the input field of reactive forms. This was not a good idea to mix your template-driven based select2 component with reactive-based approach. I have changed my reactive forms to template-driven. Everything worked
now :)
