### ISSUE TITLE
[settings] doesn't update

### ISSUE THREAD

**Issue by MrSef217** [godbasin/angular-select2#30]
Hi, 
thank you for the componant , i think i found an issue where [settings] doesn't update in :

`ngOnChanges(changes: SimpleChanges) {
    // Merge both options and data
    let settings = { data: this.options };
    if (typeof this.settings === 'object') {
      settings = Object.assign(this.settings, settings);
    }

    // Checking if the plugin is initialized
    if (this.select2 && this.select2.hasClass('select2-hidden-accessible')) {
      // Select2 has been initialized
      if (changes.options) { // <====== here
        // options change
        this.select2.empty();
        this.select2.select2(settings);
      }`

Thank you.

**Comment by godbasin** [comment]
Could you provide more detail about this please?

**Comment by MrSef217** [comment]
Hi , 
i use  the component like this   : 

`<select2 [settings]="my_settings"  [(ngModel)]="selected_client" ></select2>`

`let headers = {  "Authorization" : "something" ,  'User-ID' : "something" , other stuff ...    };`

```
this.my_settings = {
      minimumInputLength : 3,

      ajax: {

        headers : headers ,
        method : "post",
	dataType: "json",
        url: "my url" ,
	
        data : function (params) {
		// do stuff
        },
        processResults : function (data) {
               // do stuff
        }
      }
    };
```


 my_settings change dynamically but the component always keeps the first settings ,
when i checked the code i found  "if (changes.options)" is not true and this 

   ```
// options change
    this.select2.empty();
    this.select2.select2(settings);

```
doesnt get executed because in my case the object `changes` has `settings` not `options`.

version 1.1.3

Thanks.

**Comment by godbasin** [comment]
The code for `settings` changes is here:

``` js
ngOnChanges(changes: SimpleChanges) {
    // Merge both options and data
    let settings = { data: this.options };
    if (typeof this.settings === 'object') {
      settings = Object.assign(this.settings, settings);
    }
    // ...
}
```

In this way, you need to make sure:
- `this.settings` has changed, including the object reference for it.

Or:

- Other changes like `this.options`, and your `the.settings` object has updated too.

**Comment by MrSef217** [comment]
Hello , 

i think i didnt explain the issue well , 

i use the the component with '[settings]' like this :

`<select2 [settings]="my_settings" [(ngModel)]="something" ></select2> `

this piece of code never gets called after a change to `[settings]`

```
if (changes.options) { // this check changes on options , should also check on settings
    // options change
    this.select2.empty();
    this.select2.select2(settings);
  }
```

because the object `changes`  have `settings`  in my case , not `options` 

adding an or to the condition should fix the issue : 
```
if (changes.options || changes.settings) {
    // options change
    this.select2.empty();
    this.select2.select2(settings); // re aply the new settings or options 
  }
```

Thanks.

**Comment by godbasin** [comment]
Version 1.1.4 has fixed this.
