### ISSUE TITLE
Only use Static Options?

### ISSUE THREAD

**Issue by actieve** [godbasin/angular-select2#36]
Does this component not allow for changes on the [options]?

I bind to a data source that gets appended when a service returns but I never get the data shown.

**Comment by godbasin** [comment]
You can run the demo of `master` branch.

**Comment by actieve** [comment]
Yes that uses a static set of data.... In my testing if I do say an append to the data on ngoninit that data does not get added to the select2 control... Is there a function to call to say invalidate and reset the data?

**Comment by actieve** [comment]
I may have gotten it to work with just setting it once instead of appending it over and over in an iterator.

**Comment by godbasin** [comment]
You can use `[...oldData, ...appendData]` instead of append to the oldData. You need to make a new reference that can trigger the change.
