### ISSUE TITLE
 Uncaught (in promise): Error: Type Select2Component is part of the declarations of 2 modules: ProductBatchInitModule and ProductInfoInitModule! Please consider moving Select2Component to a higher module that imports 

### ISSUE THREAD

**Issue by myyue214** [godbasin/angular-select2#4]
I have moving to the higher declarations  but showing error  no  select2 can find

**Comment by godbasin** [comment]
The error shows because you have import Select2Component  twice, in both ProductBatchInitModule and ProductInfoInitModule.
Consider moving Select2Component to a higher module that imports, such as the parent module of ProductBatchInitModule and ProductInfoInitModule.
