### ISSUE TITLE
Select2Component compilation issue

### ISSUE THREAD

**Issue by bSushil** [godbasin/angular-select2#5]
I get the following error:

ERROR in ./node_modules/angular-select2-component/src/select2.component.ts
Module build failed: Error: /mnt/projects/rmis/site/node_modules/angular-select2-component/src/select2.component.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (/mnt/projects/rmis/site/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:648:23)
    at plugin.done.then (/mnt/projects/rmis/site/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./node_modules/angular-select2-component/index.ts 1:0-40
 @ ./src/app/voucher-entry/voucher-entry.component.ts
 @ ./src/app/voucher-entry/voucher-entry.module.ts
 @ ./src/$$_lazy_route_resource lazy
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

How can I fix this?
I am using angular 5 and I am new to angular.

**Comment by godbasin** [comment]
Adding the include option at the end of tsconfig.json fixed the compile issue.
Similar to #2
