### ISSUE TITLE
Cannot find angular component

### ISSUE THREAD

**Issue by bSushil** [godbasin/angular-select2#6]
I get the following error when running the application:

Error: Uncaught (in promise): Error: Template parse errors:
'select2' is not a known element:
1. If 'select2' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (">
                                    <td class="col-md-2">
                                        [ERROR ->]<select2 [(ngModel)]="theItem.revenue_head" class="form-control" name="voucheritem.revenue_head[]" re"): ng:///VoucherEntryModule/VoucherEntryComponent.html@130:40

Component is setup as per instructions given in https://www.npmjs.com/package/angular-select2-component

**Comment by godbasin** [comment]
This error appears when you haven't import the compinent into your module.


1. Import component.

``` javascript
// import NgModule
import {NgModule} from '@angular/core';
// import Select2Component
import {Select2Component} from 'angular-select2-component';

@NgModule({
  // ...
  // declare components
  declarations: [Select2Component]
})
export class YourModule {
}
```

2. Template.

``` html
<select2 [options]="options" [(ngModel)]="optionSelected" (onSelect)="onSelect($event)"></select2>
```

**Comment by bSushil** [comment]
Thanks. This works now. I guess importing the component in top level module doesn't work. I imported the component in my child module and it worked fine.
